services:
  client:
    container_name: telegraph-replica-client
    build: ./client
    image: node:19.9.0
    ports: 
      - 8080:8080
    working_dir: /code
    volumes:
      - type: bind
        source: ./client
        target: /code
    command: [ "http-server" ]
  api:
    image: node
    container_name: telegraph-replica-api
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=futureproof
      - PGHOST=db
      - PGPASSWORD=password1
      - PGDATABASE=telegraph
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run dev"

  db:
    image: postgres:12.4
    container_name: telegraph-replica-db
    volumes:
      - "./db/migrations:/docker-entrypoint-initdb.d/:ro"
    environment: 
      - POSTGRES_DB=telegraph
      - POSTGRES_USER=futureproof
      - POSTGRES_PASSWORD=password1.
volumes:
  dbdata:
networks: 
  default:
    name: telegraph-api